apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lovable
resources:
  - configmap.yaml
  - deployment.yaml
  - certificate.yaml
  - ingress.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/http-backend.json
      - dashboards/overview.json
      - dashboards/postgres.json
      - dashboards/worker.json
